### ISSUE TITLE
Master should be labled the default

### ISSUE THREAD

**Issue by spanglies** [AJEKsoft/OpenSC4#2]
It looks like Master is far ahead of main and it'd be good to either commit the changes back to main or label Master as the default branch

**Comment by AdrienJaguenet** [comment]
As you're probably aware, GitHub decided a coupe years ago that the default branch would be named "main", but git on Linux still uses "master". I'm not good enough with git to fix this mess.

**Comment by igtampe** [comment]
On GitHub you can change your default branch. Consider changing it to Master there. That, and if there are any changes on main not on master, consider making a PR to bring them in.

The other solution would be to make a PR from Master into Main, then switch to and use **origin/main** (not origin/master) when pushing to GitHub using git

**Comment by AdrienJaguenet** [comment]
This should be fixed now
